# Setup
title:               Antoine Saillenfest, PhD
tagline:             ''
description:         'Personal website. Research and stuff'
url:                 https://toinesayan.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Antoine Saillenfest
  url:               https://twitter.com/ToineSayan
  email:             saillenfest@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             ''
google_analytics_id: ''
